on:
  push:
    branches: [ master ]

jobs:
  build-and-deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '*'
    - run: npx surge . genshin-data.surge.sh --token ${{ secrets.SURGE_TOKEN }}
